//! A hand-picked list of good free plugins that run in Unplugged (VST3 or CLAP, 64-bit
//! Windows). Facts checked against each project's official page in October 2026.

pub struct FreePlugin {
    pub name: &'static str,
    pub what: &'static str,
    pub instrument: bool,
    pub formats: &'static str,
    /// "MIT", "GPL-3.0", ... or "Free (closed source)".
    pub license: &'static str,
    pub guitar: bool,
    pub url: &'static str,
}

pub const FREE_PLUGINS: &[FreePlugin] = &[
    FreePlugin {
        name: "Neural Amp Modeler",
        what: "Guitar amp and pedal sim that plays neural captures of real gear",
        instrument: false,
        formats: "VST3",
        license: "MIT",
        guitar: true,
        url: "https://www.neuralampmodeler.com/users",
    },
    FreePlugin {
        name: "AIDA-X",
        what: "Neural amp and pedal model player",
        instrument: false,
        formats: "VST3, CLAP",
        license: "GPL-3.0",
        guitar: true,
        url: "https://github.com/AidaDSP/AIDA-X/releases",
    },
    FreePlugin {
        name: "BYOD",
        what: "Build-your-own guitar pedalboard (mostly distortion)",
        instrument: false,
        formats: "VST3, CLAP",
        license: "GPL-3.0",
        guitar: true,
        url: "https://github.com/Chowdhury-DSP/BYOD/releases/latest",
    },
    FreePlugin {
        name: "ChowCentaur",
        what: "Klon Centaur overdrive pedal emulation",
        instrument: false,
        formats: "VST3",
        license: "BSD-3",
        guitar: true,
        url: "https://chowdsp.com/products.html",
    },
    FreePlugin {
        name: "Airwindows Consolidated",
        what: "About 400 Airwindows effects in one plugin, with built-in docs",
        instrument: false,
        formats: "VST3, CLAP",
        license: "MIT",
        guitar: false,
        url: "https://www.airwindows.com/consolidated/",
    },
    FreePlugin {
        name: "Dragonfly Reverb",
        what: "Hall, room, plate and early-reflection reverbs",
        instrument: false,
        formats: "VST3, CLAP",
        license: "GPL-3.0",
        guitar: false,
        url: "https://michaelwillis.github.io/dragonfly-reverb/",
    },
    FreePlugin {
        name: "ChowTapeModel",
        what: "Analog reel-to-reel tape warmth",
        instrument: false,
        formats: "VST3",
        license: "GPL-3.0",
        guitar: false,
        url: "https://chowdsp.com/products.html",
    },
    FreePlugin {
        name: "ChowMatrix",
        what: "Branching, modulated delay",
        instrument: false,
        formats: "VST3",
        license: "BSD-3",
        guitar: false,
        url: "https://chowdsp.com/products.html",
    },
    FreePlugin {
        name: "ChowMultiTool",
        what: "EQ, filters and other mixing tools",
        instrument: false,
        formats: "VST3, CLAP",
        license: "Open source",
        guitar: false,
        url: "https://chowdsp.com/products.html",
    },
    FreePlugin {
        name: "Surge XT (+ Surge XT Effects)",
        what: "Big hybrid synth; the installer also includes its effects as a separate plugin",
        instrument: true,
        formats: "VST3, CLAP",
        license: "GPL-3.0",
        guitar: false,
        url: "https://surge-synthesizer.github.io/",
    },
    FreePlugin {
        name: "Valhalla Supermassive",
        what: "Huge ambient reverb and delay",
        instrument: false,
        formats: "VST3",
        license: "Free (closed source)",
        guitar: false,
        url: "https://valhalladsp.com/shop/reverb/valhalla-supermassive/",
    },
    FreePlugin {
        name: "Vital",
        what: "Wavetable synth (the free Basic tier is the full synth)",
        instrument: true,
        formats: "VST3, CLAP",
        license: "Free (closed installers)",
        guitar: false,
        url: "https://vital.audio/",
    },
    FreePlugin {
        name: "Odin 2",
        what: "24-voice semi-modular synth",
        instrument: true,
        formats: "VST3, CLAP",
        license: "GPL-3.0",
        guitar: false,
        url: "https://thewavewarden.com/odin2",
    },
    FreePlugin {
        name: "Cardinal",
        what: "VCV Rack modular synth and effects in a plugin",
        instrument: true,
        formats: "VST3, CLAP",
        license: "GPL-3.0",
        guitar: false,
        url: "https://github.com/DISTRHO/Cardinal/releases",
    },
];

/// A much longer community list of free effect plugins.
pub const MORE_FREE_PLUGINS_URL: &str = "https://github.com/twinysam/FreeAudioPluginList";
